services:
  cassandra:
    image: docker.io/bitnami/cassandra:latest
    environment:
      CASSANDRA_PASSWORD_SEEDER: yes
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
    ports:
      - "9042:9042"
